apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/valeriefan/notification-service/k8s?ref=master

patches:
  - path: patch-env.yml

configMapGenerator:
  - behavior: merge
    files:
      - application-staging.yml
    name: notification-config

images:
  - name: dispatcher-service
    newName: ghcr.io/valeriefan/notification-service
    newTag: latest

replicas:
  - name: dispatcher-service
    count: 1
