apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  template:
    spec:
      containers:
        - name: notification-service
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: staging
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9003
            initialDelaySeconds: 30  # Increased delay
            periodSeconds: 15
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9003
            initialDelaySeconds: 30  # Increased delay
            periodSeconds: 15
            timeoutSeconds: 1