apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/valeriefan/catalog-service/k8s?ref=master

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: catalog-config

images:
- name: catalog-service
  newName: ghcr.io/valeriefan/catalog-service
  newTag: 190937c4cb8adcd98df082d8315215ed44b0317c

replicas:
- count: 2
  name: catalog-service
