spring:
  config:
    import: configtree:/workspace/secrets/*/

  autoconfigure:
    exclude=org:
      springframework:
        boot:
          autoconfigure:
            data:
              redis:
                RedisAutoConfiguration,org:
                  springframework:
                    boot:
                      autoconfigure:
                        data:
                          redis:
                            RedisRepositoriesAutoConfiguration: