apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/valeriefan/edge-service/k8s?ref=master

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml
- path: patch-ingress.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: edge-config

images:
- name: edge-service
  newName: ghcr.io/valeriefan/edge-service
  newTag: 50f9bf0b5f0325f03556994c4d536442dbb01620

replicas:
- count: 1
  name: edge-service
