apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/valeriefan/notification-service/k8s?ref=master

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: notification-config

images:
- name: notification-service
  newName: ghcr.io/valeriefan/notification-service
  newTag: 5006acccdb2d44deee349962df5ea9c40b44bef6

replicas:
- count: 1
  name: notification-service
